name: Releases 📦

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - run: make pack-extensions
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'regexper-ng*.vsix'
          token: ${{ secrets.AUTOMATION_SECRET }}
